### PR TITLE
Rollup of download work

### PR DESCRIPTION
**Pull request by olsonanl**
This req has the commits for the download work (and apparently some Tom stuff that I pulled into this fork).

### CODE REVIEW

**Comment by brettin** [comment]
Some of the listed tests no longer work. Still need to  clean up the test directory for the client tests.

**Comment by olsonanl** [comment]
is that from my changes or from changes to the tests?

On Feb 9, 2015, at 6:17 PM, Thomas Brettin <notifications@github.com<mailto:notifications@github.com>> wrote:

Some of the listed tests no longer work. Still need to clean up the test directory for the client tests.

**Comment by brettin** [comment]
They are from the overhaul of the API. Legacy. I’d just like to clean it out when I get a spare min.

**Comment by olsonanl** [comment]
Got it, thanks.

On Feb 10, 2015, at 10:57 AM, Thomas Brettin <notifications@github.com<mailto:notifications@github.com>> wrote:

They are from the overhaul of the API. Legacy. I’d just like to clean it out when I get a spare min.

**Pull request merged**
